package dev.gaudnik.id_jpa.data.repository;

import dev.gaudnik.id_jpa.data.entity.StudentAutoGeneratedId;
import org.springframework.data.jpa.repository.JpaRepository;

public interface StudentAutoGeneratedIdRepository extends JpaRepository<StudentAutoGeneratedId, Long> {
}
